### PR TITLE
Fix missing namespace onMessageExternal

### PR DESCRIPTION
**Pull request by freaktechnik**
😱 Sorry about that, currently trying to test it with my extension and will then publish a beta version that supports using this API.

### CODE REVIEW

**Comment by freaktechnik** [comment]
I've now published the beta that is compatible with this (in case you want to test if the API actually works, it worked locally for me on linux, though I had to use a temp install because the extension is marked incompatible): https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/beta?page=1#version-3.6.0pre01

**Comment by plneappl** [comment]
Your Add-on calls mine with an array as url argument on twitch (www.twitch.tv/channel and go.twitch.tv/channel). I've added error handling to the API to return more meaningful errors.
I didn't just use the first array element, since calling a function on a list can have multiple meanings: apply to all, apply to some (and to which?); also the list might be empty, and more special cases/error detection is bad most of the time.
So please fix that on your end, otherwise it seems to work now :)

**Comment by plneappl** [comment]
If you have the time, could you please write down the setup for linux users? 
Then I can mark it as compatible with linux, too.

**Comment by freaktechnik** [comment]
> Your Add-on calls mine with an array as url 

oh, that's right, my bad. I only tested with "external" channels, like the ones in the explore tab that directly get a channel. I didn't mean to ever call it with a non-string (and shouldn't new URL throw in that case?)

**Comment by freaktechnik** [comment]
> If you have the time, could you please write down the setup for linux users?
> Then I can mark it as compatible with linux, too.

I've added it to my todo list.

**Comment by plneappl** [comment]
It throws an error, which is ignored? Or is it optimized away, since the object is not used? In any case, it just silently goes through and confuses streamlink.

**Pull request merged**
